---
- name: Base hardening and firewall
  hosts: all
  become: true
  roles:
    - role: base
    - role: firewall

- name: Provision GPU
  hosts: all
  become: true
  roles:
    - role: gpu

- name: Provision k3s server
  hosts: all
  become: true
  roles:
    - role: k3s_server
