---
- name: Base hardening and firewall
  hosts: all
  become: true
  roles:
    - role: base
    - role: firewall

- name: Provision GPU
  hosts: all
  become: true
  roles:
    - role: gpu

- name: Provision k3s server
  hosts: all
  become: true
  pre_tasks:
    - name: Install Ansible collections
      delegate_to: localhost
      run_once: true
      become: false
      ansible.builtin.command:
        cmd: ansible-galaxy collection install -r ../requirements.yml -p ../collections
        chdir: "{{ playbook_dir }}"
      changed_when: false

    - name: Install Python dependencies for Ansible
      delegate_to: localhost
      run_once: true
      become: false
      ansible.builtin.command:
        cmd: pipx inject ansible-core kubernetes
      changed_when: false

  roles:
    - role: k3s_server
