version: "3"

includes:
  tools:
    taskfile: ./taskfiles/tools.yml
    flatten: true
  bootstrap:
    taskfile: ./taskfiles/bootstrap.yml
    flatten: true
  kubeconfig:
    taskfile: ./taskfiles/kubeconfig.yml
    flatten: true
  flux:
    taskfile: ./taskfiles/flux.yml
    flatten: true
  lint:
    taskfile: ./taskfiles/lint.yml
    flatten: true

vars:
  ROOT_DIR:
    sh: git rev-parse --show-toplevel

  ANSIBLE_DIR: bootstrap/ansible
  INVENTORY: inventory/homelab.yml
  ANSIBLE_PLAYBOOK: ansible-playbook -i "{{.INVENTORY}}"

  TOOLS_DIR: "{{.ROOT_DIR}}/.tools"
  TOOLS_BIN: "{{.TOOLS_DIR}}/bin"
  FLUX_VERSION: v2.8.6
  GH_VERSION: v2.90.0

  KUBECTL_VERSION: v1.35.3
  KUBECONFIG_DIR:
    sh: printf '%s/.kube/tinycloud' "$HOME"
  KUBECONFIG_LOCAL: "{{.KUBECONFIG_DIR}}/config"
  KUBECONFIG_CLUSTER: default
  K3S_SERVER_URL: https://zion:6443

  FLUX_GITHUB_OWNER: sojournerdev
  FLUX_GITHUB_REPOSITORY: tinycloud
  FLUX_GITHUB_BRANCH: main
  FLUX_CLUSTER_PATH: clusters/tinycloud
