apiVersion: v1
kind: Secret
metadata:
    name: oci-registry-auth
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:fGmVq6FwfKq9F5+wTTCoX8ZYt1o07yLqKBFi4rMKytKq6OqCY4jDlwWO8t9Hqhf47ih2vEj5TPYoq9gKF2vM1IkSUaY=,iv:BEcceMlSc7UejuBrUvwySiRETWr8kibVuMwKh7ykSFE=,tag:D5cvWGHuwhJOrQhmrNaWow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5SElvVlhJdm0wNCs3eity
            MVB3WWNkcmNPa2xrZFVjTmdzVTBvNWw3cGh3ClNWUitMR1p6VjFxakxva3Z6Vlha
            ZHdTbW5tdFpuc3ZwamU4S0c2bFI2dWcKLS0tIEJ5dGJrTkFhQWtzUEpzQmlDK0ZF
            bEVQRlhLQmliaGN0dHkzUTlvREpNTmsKBEwm3jCJ4bylhA9Q+f5TuKwCVOz2ktzG
            uhyuBlFLy8lb8DoXLRBQQESN1kUUAUglLqTc9AB7sPi9R73+FVRr4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hvn6a2qlvc2wzzax29psfxxuwrc58xv0226ysuphpr3dnhr5k4ysmwv087
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T22:07:17Z"
    mac: ENC[AES256_GCM,data:3UG743NKqS4ejmRT8Y/sdZz+vf0axAntRL7ugeNOJFmSE5W54kgc4rOkAq9yDTtaUapl0Bt+3j4hNAZo6BfVF1Ag13SRUw910+WIdhQrZL/KmSGNl6D79m+KV+JXAfGhcIpsnVmoVGMk58LzmFoNSYTVjj7XOxCnd8nAKhYdYmo=,iv:aLVHvEnVMimyULuBO5MVY2KgJqfA1blm0CRJDTbPkuo=,tag:gg9VF/KuoUfHVdCfs35g1w==,type:str]
    version: 3.13.3
